Make emitted event kebab-case, to support using in-DOM templates
spatie/vue-table-component pull request #138
Opened 2018-03-12 23:23 UTC by davidavz

HTML attributes are case-insensitive and you cannot use v-on to listen to camelCase events when using in-DOM templates. 

We should use "row-click" instead of "rowClick".

[vuejs/vue#5186 (comment)](https://github.com/vuejs/vue/issues/5186#issuecomment-286304512)

2018-03-13 08:06 UTC, freekmurze requested changes

2018-03-13 08:06 UTC, freekmurze commented on src/components/TableRow.vue
> +    <tr @click="$emit('row-click', row)">
Changing this will break backwards compatibility.

Could you fix this by emitting both `row-click` and `rowClick`?

2018-03-13 08:06 UTC, freekmurze commented on src/components/TableComponent.vue
> +						@row-click="emitRowClick"
Remove this change (see below)

2018-03-13 08:06 UTC, freekmurze commented on src/components/TableComponent.vue
> +				this.$emit('row-click', row);
Remove this change (see below)

2018-03-14 08:59 UTC, davidavz commented
I am now emitting both `row-click` and `rowClick`

2018-03-14 18:52 UTC, merged

2018-03-14 18:52 UTC, freekmurze commented
Thanks!

2018-08-23 09:11 UTC, fritx commented
Excuse me.. what does "in-DOM template" mean?